'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Win8To7_Setup_Mode_Phases.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_9200_all_setupfile_Glass8_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_9200_all_setupfile:Glass8.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_9200_SMEx7ForWin8_setupfile_ex7forw8_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_9200_SMEx7ForWin8_setupfile:ex7forw8.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_9200_SMStartIsBack_setupfile_StartIsBack_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_9200_SMStartIsBack_setupfile:StartIsBack.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_9600_all_setupfile_Glass8_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_9600_all_setupfile:Glass8.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_9600_SMStartIsBack_setupfile_StartIsBack_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_9600_SMStartIsBack_setupfile:StartIsBack.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setupfile_7GamesInstaller_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setupfile:7GamesInstaller.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setupfile_7tt_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setupfile:7tt.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setupfile_ClassicTM_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setupfile:ClassicTM.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setupfile_GadgetInstaller_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setupfile:GadgetInstaller.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setupfile_UXThemePatcher_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setupfile:UXThemePatcher.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setuptool_ResourceHacker_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setuptool:ResourceHacker.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_SMOpenShell_setupfile_OpenShellSetup_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_SMOpenShell_setupfile:OpenShellSetup.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property amd64_all_all_setuptool_regchange_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("amd64_all_all_setuptool:regchange.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property i386_all_all_setuptool_regchange_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("i386_all_all_setuptool:regchange.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_BackDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_BackDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_BackHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_BackHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_BackNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_BackNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_BackPressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_BackPressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_SetupBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_SetupBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property progressspinner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progressspinner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win7enterprisebranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win7enterprisebranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win7homebranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win7homebranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win7probranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win7probranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win7starterbranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win7starterbranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win7ultimatebranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win7ultimatebranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win8enterprisebranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win8enterprisebranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win8homebranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win8homebranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win8probranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win8probranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win8starterbranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win8starterbranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
