'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Win8To7_Transformation_Pack_Backend.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_9200_all_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_9200_all_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_9200_all_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_9200_all_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_9600_all_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_9600_all_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_9600_all_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_9600_all_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setuptool_7z_License_txt() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setuptool:7z License.txt", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setuptool_7za_dll() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setuptool:7za.dll", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setuptool_7za_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setuptool:7za.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setuptool_7zxa_dll() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setuptool:7zxa.dll", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_setuptool_setup_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_setuptool:setup.exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_all_userlocation() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_all_userlocation", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Allow7Gadgets_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Allow7Gadgets_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_AllowUserCPL_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_AllowUserCPL_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Branding7Enterprise_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Branding7Enterprise_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Branding7Home_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Branding7Home_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Branding7Pro_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Branding7Pro_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Branding7Starter_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Branding7Starter_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Branding7Ult_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Branding7Ult_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Branding8Enterprise_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Branding8Enterprise_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Branding8Home_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Branding8Home_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Branding8Pro_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Branding8Pro_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Branding8Starter_res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Branding8Starter_res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_NotPro_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_NotPro_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_NotStarter_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_NotStarter_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_ReduceWinX_userlocation() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_ReduceWinX_userlocation", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_ShinelessTheme_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_ShinelessTheme_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_ShineTheme_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_ShineTheme_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_SMOpenShell_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_SMOpenShell_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_SMStartIsBack_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_SMStartIsBack_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property all_all_Starter_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("all_all_Starter_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property amd64_9200_all_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("amd64_9200_all_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property amd64_9600_all_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("amd64_9600_all_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property amd64_9600_AllowMediaCenter_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("amd64_9600_AllowMediaCenter_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property amd64_9600_AllowShell32_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("amd64_9600_AllowShell32_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property amd64_all_7Ribbon_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("amd64_all_7Ribbon_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property amd64_all_all_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("amd64_all_all_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property amd64_all_DPRibbon_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("amd64_all_DPRibbon_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property i386_all_7Ribbon_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("i386_all_7Ribbon_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property i386_all_all_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("i386_all_all_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property i386_all_DPRibbon_location() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("i386_all_DPRibbon_location", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_amogus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_amogus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_Automatic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_Automatic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_BackDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_BackDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_BackHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_BackHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_BackNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_BackNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_BackPressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_BackPressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_ButtonHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_ButtonHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_ButtonPressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_ButtonPressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_Chocolate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_Chocolate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_ex7forw8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_ex7forw8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_ForwardHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_ForwardHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_ForwardNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_ForwardNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_ForwardPressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_ForwardPressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_openshell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_openshell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_SetupBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_SetupBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_SetupLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_SetupLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_startisback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_startisback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_themenoshine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_themenoshine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_themeshine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_themeshine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win7enterprisebranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win7enterprisebranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win7homebranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win7homebranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win7probranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win7probranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win7ribbon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win7ribbon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win7starterbranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win7starterbranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win7ultimatebranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win7ultimatebranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win8enterprisebranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win8enterprisebranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win8homebranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win8homebranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win8probranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win8probranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win8ribbon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win8ribbon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_win8starterbranding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_win8starterbranding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property int_wut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("int_wut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
